export default
    [
        {
                path: '/',
                name: 'Layout',
                component:()=>import('../views/LayOut'),
                children:[{
                    path:"/index",
                    name:"index",
                    component:()=>import("@/views/index/HomeIndex.vue")
                },
                {
                    path:"/orders/list",
                    name:"orders_list",
                    component:()=>import("@/views/order/OrderList"),
                    meta:{bread:["订单管理","订单列表"]}
                },
                {
                    path:"/waybill/in",
                    name:"wayin",
                    component:()=>import("@/views/waybill/WayIn"),
                    meta:{bread:["运单管理","运单录入"]}
                },
                {
                    path:"/waybill/list",
                    name:"waylist",
                    component:()=>import("@/views/waybill/WayList"),
                    meta:{bread:["运单管理","运单列表"]}
                },
            ],
                redirect:"/index",
            },
            {
                path:'/login',
                name:'Login',
                component:()=>import('../views/LogIn')
            },
            {
                path:"/*",
                name:"NotFound",
                component:()=>import("@/views/NotFound")
            }
    ]
