//公共路由
export default[
    {
        path:"/login",
        name:"login",
        component:()=>import('@/views/LoGin'),
    },
    {
        path:"/",
        name:"layout",
        component:()=>import('@/views/LayOut'),
        children:[
            {
                path:"/home",
                name:"home",
                component:()=>import("@/views/homepage/HomePage"),
                meta:{keepAlive:true}
            },
            {
                path:"/bookmage",
                name:"bookmage",
                component:()=>import("@/views/bookmage/BookMage"),
                meta:{keepAlive:false}
            },
            {
                path:"/sitemage/detail",
                name:"sitedetail",
                component:()=>import("@/views/sitemage/SiteDetail"),
                meta:{keepAlive:false}
            },
            {
                path:"/sitemage/rule",
                name:"siterule",
                component:()=>import("@/views/sitemage/SiteRule"),
                meta:{keepAlive:false}
            },
            {
                path:"/frontdesk",
                name:"frontdesk",
                component:()=>import("@/views/frontdesk/FrontDesk"),
                meta:{keepAlive:false}
            },
            {
                path:"/percen/index",
                name:"percenindex",
                component:()=>import("@/views/percen/PercenIndex"),
                meta:{keepAlive:false}
            },
            {
                path:"/percen/psw",
                name:"percenpsw",
                component:()=>import("@/views/percen/PercenPsw"),
                meta:{keepAlive:false}
            },
            {
                path:"/manage/user",
                name:"manage",
                component:()=>import("@/views/manage/ManageUser"),
                meta:{keepAlive:false}
            }
        ],
        redirect:"/home"
    },
    {
        path:"*",
        name:"NotFound",
        component:()=>import("@/views/NotFound")
    }
]